language: node_js
_aliases:
  - &node-prod # This is the NodeJS version we run in production.
    node_js: '10'

cache:
  yarn: true

# See: https://github.com/mozilla/addons-frontend/issues/3034
install: yarn install --pure-lockfile

matrix:
  fast_finish: true

jobs:
  include:
    # Make sure we can build a production release.
    - name: build release
      <<: *node-prod
      script: yarn build:release
    - name: unit tests
      <<: *node-prod
      script: yarn test
    - name: prettier
      <<: *node-prod
      script: yarn prettier-ci
    - name: linter
      <<: *node-prod
      script: yarn lint
